require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Backend::DesignsController do

  # This should return the minimal set of attributes required to create a valid
  # Backend::Design. As you add validations to Backend::Design, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Backend::DesignsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all backend_designs as @backend_designs" do
      design = Backend::Design.create! valid_attributes
      get :index, {}, valid_session
      assigns(:backend_designs).should eq([design])
    end
  end

  describe "GET show" do
    it "assigns the requested backend_design as @backend_design" do
      design = Backend::Design.create! valid_attributes
      get :show, {:id => design.to_param}, valid_session
      assigns(:backend_design).should eq(design)
    end
  end

  describe "GET new" do
    it "assigns a new backend_design as @backend_design" do
      get :new, {}, valid_session
      assigns(:backend_design).should be_a_new(Backend::Design)
    end
  end

  describe "GET edit" do
    it "assigns the requested backend_design as @backend_design" do
      design = Backend::Design.create! valid_attributes
      get :edit, {:id => design.to_param}, valid_session
      assigns(:backend_design).should eq(design)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Backend::Design" do
        expect {
          post :create, {:backend_design => valid_attributes}, valid_session
        }.to change(Backend::Design, :count).by(1)
      end

      it "assigns a newly created backend_design as @backend_design" do
        post :create, {:backend_design => valid_attributes}, valid_session
        assigns(:backend_design).should be_a(Backend::Design)
        assigns(:backend_design).should be_persisted
      end

      it "redirects to the created backend_design" do
        post :create, {:backend_design => valid_attributes}, valid_session
        response.should redirect_to(Backend::Design.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved backend_design as @backend_design" do
        # Trigger the behavior that occurs when invalid params are submitted
        Backend::Design.any_instance.stub(:save).and_return(false)
        post :create, {:backend_design => { "name" => "invalid value" }}, valid_session
        assigns(:backend_design).should be_a_new(Backend::Design)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Backend::Design.any_instance.stub(:save).and_return(false)
        post :create, {:backend_design => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested backend_design" do
        design = Backend::Design.create! valid_attributes
        # Assuming there are no other backend_designs in the database, this
        # specifies that the Backend::Design created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Backend::Design.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => design.to_param, :backend_design => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested backend_design as @backend_design" do
        design = Backend::Design.create! valid_attributes
        put :update, {:id => design.to_param, :backend_design => valid_attributes}, valid_session
        assigns(:backend_design).should eq(design)
      end

      it "redirects to the backend_design" do
        design = Backend::Design.create! valid_attributes
        put :update, {:id => design.to_param, :backend_design => valid_attributes}, valid_session
        response.should redirect_to(design)
      end
    end

    describe "with invalid params" do
      it "assigns the backend_design as @backend_design" do
        design = Backend::Design.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Backend::Design.any_instance.stub(:save).and_return(false)
        put :update, {:id => design.to_param, :backend_design => { "name" => "invalid value" }}, valid_session
        assigns(:backend_design).should eq(design)
      end

      it "re-renders the 'edit' template" do
        design = Backend::Design.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Backend::Design.any_instance.stub(:save).and_return(false)
        put :update, {:id => design.to_param, :backend_design => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested backend_design" do
      design = Backend::Design.create! valid_attributes
      expect {
        delete :destroy, {:id => design.to_param}, valid_session
      }.to change(Backend::Design, :count).by(-1)
    end

    it "redirects to the backend_designs list" do
      design = Backend::Design.create! valid_attributes
      delete :destroy, {:id => design.to_param}, valid_session
      response.should redirect_to(backend_designs_url)
    end
  end

end
