development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: resume_creator_development
  pool: 5
  username: root
  password: passw0rd

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: resume_creator_test
  pool: 5
  username: root
  password: passw0rd
